counties=["AB", "AR", "AG", "BC", "BH", "BN", "BR", "BT", "BV", "BZ", "CS", "CL", "CJ", "CT", "CV", "DB", "DJ", "GL", "GR", "GJ", "HR", "HD", "IL", "IS", "IF", "MM", "MH", "MS", "NT", "OT", "PH", "SM", "SJ", "SB", "SV", "TR", "TM", "TL", "VS", "VL", "VN"]
bucharest="B"
license_plate=[]
letters=["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
comb=[]
for i in range(25):
    for j in range(25):
        for k in range(25):
            if (letters[i] != "I" and letters[i] != "O") :
                comb.append(letters[i]+letters[j]+letters[k])
comb.remove("ASS")
comb.remove("BES")
comb.remove("BOU")
comb.remove("CCT")
comb.remove("CMO")
comb.remove("COW")
comb.remove("COX")
comb.remove("COY")
comb.remove("CUR")
comb.remove("EBU")
comb.remove("EBY")
comb.remove("FAC")
comb.remove("FAK")
comb.remove("FUC")
comb.remove("FUK")
comb.remove("FUT")
comb.remove("GAD")
comb.remove("GAY")
comb.remove("GEI")
comb.remove("GEY")
comb.remove("HAM")
comb.remove("HER")
comb.remove("HUI")
comb.remove("HUY")
comb.remove("JID")
comb.remove("KAL")
comb.remove("KIZ")
comb.remove("KOI")
comb.remove("KOX")
comb.remove("KUR")
comb.remove("KZD")
comb.remove("LOH")
comb.remove("MUE")
comb.remove("MUI")
comb.remove("MUL")
comb.remove("PIZ")
comb.remove("PMR")
comb.remove("POH")
comb.remove("PUC")
comb.remove("PUK")
comb.remove("PUL")
comb.remove("PUT")
comb.remove("PZD")
comb.remove("RAB")
comb.remove("RAG")
comb.remove("SEX")
comb.remove("SRI")
comb.remove("SRU")
comb.remove("SSX")
comb.remove("SUG")
comb.remove("VOR")
comb.remove("WOR")
comb.remove("WTF")
comb.remove("XER")
comb.remove("XUI")
comb.remove("XUY")
comb.remove("XYI")
comb.remove("YBI")
comb.remove("YBL")
comb.remove("YBU")
comb.remove("ZAD")
comb.remove("ZEC")
comb.remove("ZEK")
comb.remove("ZOI")
comb.remove("ZOY")
comb.remove("POL")
comb.remove("DEP")
comb.remove("SNT")
comb.remove("GUV")
comb.remove("MAI")
comb.remove("ALA")
comb.remove("COI")
comb.remove("DAI")
comb.remove("PIX")
comb.remove("TOV")
comb.remove("ROM")
comb.remove("POC")
comb.remove("PLM")
comb.remove("BOY")
comb.remove("JAF")
comb.remove("JEG")
comb.remove("KGB")
comb.remove("XXX")
for i in range(41):
    for j in range(1,100):
        for word in comb:
            if j<10:
                license_plate.append(counties[i]+str('0')+str(j)+word)
            else:
                license_plate.append(counties[i]  + str(j) + word)
for j in range(100,999):
    for word in comb:
            license_plate.append(bucharest+str(j)+word)
f=open("nr.txt","w")
for i in license_plate:
    f.write(i+'\n')
print(len(license_plate))


